# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/gta4xlswifi/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),gta4xlswifi)

$(call add-radio-file-sha1-checked,radio/fld.bin_SM-P620,e3869b4ea8c71f49144dd1b4d5bd8483bd99e515)
$(call add-radio-file-sha1-checked,radio/harx.bin_SM-P620,459e3b30b61ef7fe9278983d235e351d780a7d93)
$(call add-radio-file-sha1-checked,radio/keystorage.bin_SM-P620,82b177250660628381a06c8dcccfa2778ee228dc)
$(call add-radio-file-sha1-checked,radio/ldfw.img_SM-P620,f6b06bd52ee9428df3c8eff26cf95f49c8c7c79e)
$(call add-radio-file-sha1-checked,radio/models,e0296de6d57b6e5c07758d7cd41298bf6ea41793)
$(call add-radio-file-sha1-checked,radio/modem.bin_SM-P620,a55a41d4dc4337454067cfff8ca5391807211c6a)
$(call add-radio-file-sha1-checked,radio/modem_debug.bin_SM-P620,f161ebd29699d93411cec0915c5133c0f3229a28)
$(call add-radio-file-sha1-checked,radio/sboot.bin_SM-P620,c32710b9670d0b32da0331abededdc20228737ec)
$(call add-radio-file-sha1-checked,radio/tzar.img_SM-P620,981a31a6857ac338b3dd48d65084df1b04443e85)
$(call add-radio-file-sha1-checked,radio/tzsw.img_SM-P620,3a4a3f8c0c9e4f1065d7aed9ebfd7c585166f450)
$(call add-radio-file-sha1-checked,radio/uh.bin_SM-P620,cd92125773c57221ec0ee33f2041c82b1d16ef88)
$(call add-radio-file-sha1-checked,radio/up_param.bin_SM-P620,efc8dcd93bc37fc0b26da6bbf11f3ceac39918e4)
$(call add-radio-file-sha1-checked,radio/version_SM-P620,3e9575d742642e60900387e541f1fac00a2cce9c)

endif
