# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/gta4xlswifi/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),gta4xlswifi)

$(call add-radio-file-sha1-checked,radio/cm.bin_SM-P610,)
$(call add-radio-file-sha1-checked,radio/keystorage.bin_SM-P610,)
$(call add-radio-file-sha1-checked,radio/models,)
$(call add-radio-file-sha1-checked,radio/sboot.bin_SM-P610,)
$(call add-radio-file-sha1-checked,radio/uh.bin_SM-P610,)
$(call add-radio-file-sha1-checked,radio/up_param.bin_SM-P610,)
$(call add-radio-file-sha1-checked,radio/version_SM-P610,)

endif
